### ISSUE TITLE
Position of signature is not as in primary identity

### ISSUE THREAD

**Issue by knilde** [Jabb0/CatchAllBird#8]
Hello,

seems to me that the signature of automatically created identities are not correctly taken from the primary identity.

My setting in primary identity is 
![grafik](https://user-images.githubusercontent.com/79543337/188633734-f5fb9719-f4f4-4207-b724-efe0a376fa79.png)

Translation of the red marked setting is:
Place my signature under my reply but above the quoted text.

Here a newly created auto-identity with wrong setting marked:
![grafik](https://user-images.githubusercontent.com/79543337/188634313-4ffa33d6-28eb-48c4-91c4-2cfe10ba7a19.png)

Thanks for this really useful addin !! =)

**Comment by Jabb0** [comment]
Hello,

thanks for the feedback.

This issue has the same cause as #6 
As of now Thunderbird does not support to copy this information when creating a new identity.

We need to wait until this functionality is added or implement an "experimental" functionality.

**Comment by knilde** [comment]
Ah, OK. Good you allready know. :-)
As workaround (and for max user satisfaction) you COULD add the setting to your preferences site.

**Comment by Jabb0** [comment]
Thanks for the suggestion :)
Unfortunately, it is not possible to change this setting with an AddOn at all. The AddOn interface is still in development I guess.

Next step is to create a bug report / feature request for Thunderbird.

**Comment by knilde** [comment]
OK. Thanks for Information.
Where can I put the feature request for Thunderbird?

**Comment by Jabb0** [comment]
I guess this is the place:
https://bugzilla.mozilla.org/home

The issue is missing information in the https://webextension-api.thunderbird.net/en/102/identities.html
API.

MailIdentity does not have all identify information. For example, about the SMTP server or the signature position. 
The SMTP server for the new identity is then set to the default one of the installation. This is unexpected behaviour.
The signature positioning is just the default I guess.
One needs to ask to add this functionality to the API.

I can open a bug/feature request next week.
But feel free to do it if you like :)

**Comment by knilde** [comment]
I would do but it's better if you can do it. So there is a chance developers there can ask questions and get a response :-)
